name-template: 'v$NEXT_PATCH_VERSION 🌈'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'security vulnerability'
  - title: '🧰 Maintenance'
    labels:
      - 'dependencies'
      - 'infrastructure'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## What's Changed
  $CHANGES
filter-by-commitish: true